# Oracle Server Configuration

# Below is the list of default configuration for oracle server:
logLevel: 3  # Logging verbosity: 0: NoLevel, 1: Trace, 2: Debug, 3: Info, 4: Warn, 5: Error
gasTipCap: 1000000000  # 1GWei, the gas priority fee cap for oracle vote message which will be reimbursed by Autonity network.

#Set the buffering time window in blocks to continue vote after the last penalty event. Default value is 86400 (1 day).
#With such time buffer, the node operator can check and repair the local infra without being slashed due to the voting.
#This is important for node operator to prevent node from getting slashed again.
voteBuffer: 86400  # Buffer time in seconds (3600 * 24)

#Set oracle server key file.
keyFile: "./UTC--2023-02-27T09-10-19.592765887Z--b749d3d83376276ab4ddef2d9300fb5ce70ebafe"

#Set the password to decrypt oracle server key file.
keyPassword: "123%&%^$"  # Password for the key file

#Set the WS-RPC server listening interface and port of the connected Autonity Client node.
autonityWSUrl: "ws://127.0.0.1:8546"

#Set the directory of the data plugins.
pluginDir: "./plugins"  # Directory for plugins

#Set the profiling report directory, where some runtime state will be saved at.
profileDir: "."  # Profile directory

#Confidence and confidence strategies:
#Each plugin can be configured with a confidence value within the range of [1, 100]. A higher confidence value
#indicates better data quality provided by the data source. User can config multiple plugins of different data sources
#to maintain high availability of data, setting one of them with higher confidence as primary, and the others as backup
# with lower confidence.

# Available strategies:
# When there are multiple data sources, the strategies determine the data aggregation and confidence computing:
# 0: max - Selects the data sample from the plugin with the highest confidence for data reporting.
#  In the plugin config section, users can assign a confidence value (ranging from [1 to 100]) to each plugin.
#  When multiple samples from different data sources have equal confidence, for currencies without collected volume data,
#  it performs a confidence - weighted price calculation for data submission.

# 1: aggregated - For currencies without collected volume data, it uses a confidence - weighted price for data submission.
#  For currencies with collected volume data, it takes a volume - weighted price for submission.
confidenceStrategy: 0  # 0: max, 1: aggregated, default value is 0.

#Set the plugin configs.
# The forex data plugins are used to fetch realtime rate of currency pairs:
# EUR-USD, JPY-USD, GBP-USD, AUD-USD, CAD-USD and SEK-USD from commercial data providers. There are 4 implemented forex
# data plugins, each of them requires the end user to apply for their own service key from the selected data provider.
# The selection of which forex data plugin(s) to use is for the end user to decide. The user can use any one of them,
# or he/she can use multiple forex data plugins in the setup.
#
# The crypto data plugins are used to fetch market prices for the crypto currency pairs: ATN-USDC, NTN-USDC, NTN-ATN and
# USDC-USD. USDC liquidity is bridged to the Autonity public testnet from the Polygon Amoy testnet via a bridge service.
# Out-the-box plugins for collecting ATN-USDC and NTN-USDC market data are available for UniSwap V2 and AirSwap protocols.
# NTN-ATN market price is derived from that market data, and USDC pricing is converted to USD. ATN-NTN, ATN-USD, and
# NTN-USD prices are then submitted on-chain. To retrieve ATN and NTN prices, put the `crypto_uniswap` plugin in your plugin directory.
# Oracle server can then discover and load them. Configuring the `crypto_uniswap` plugin does not require an API key,
# it is an open and free data source of a standard EVM RPC websocket service endpoint. The end user can connect to specific
# EVM RPC endpoint base on the blockchain which hosts the uniswap contract.

# USDC-USD prices are required by the protocol to convert the ATN-USDC and NTN-USDC to ATN-USD and NTN-USD. This enables
# the reporting of ATN and NTN prices in USD to the ASM. Three plugins are implemented to source the USDC-USD datapoint
# from open and free data sources: coinbase, coingecko, and kraken. To prevent single data source failure, putting all
# 3 plugins of CEX into your plugin directory is recommended. Oracle server can then discover and load them.
# You don't need to configure the CEX plugins (crypto_coinbase, crypto_coingecko, crypto_kraken) in your oracle server
# plugin configuration file.

# For the forex data plugin default configuration is set, so the end user just needs to configure required settings,
# namely `name` and `key`. The configuration settings of a plugin are:
#

#  // PluginConfig is the schema of plugins' config.
#  type PluginConfig struct {
#  Name               string `json:"name" yaml:"name"`         // The name of the plugin binary.
#  Key                string `json:"key" yaml:"key"`           // The API key granted by your data provider to access their data API.
#  Scheme             string `json:"scheme" yaml:"scheme"`     // The data service scheme, http or https.
#  Disabled           bool   `json:"disabled" yaml:"disabled"` // The flag to disable a plugin.
#  Endpoint           string `json:"endpoint" yaml:"endpoint"` // The data service endpoint url of the data provider.
#  Timeout            int    `json:"timeout" yaml:"timeout"`   // The timeout period in seconds that an API request is lasting for.
#  DataUpdateInterval int    `json:"refresh" yaml:"refresh"`   // The interval in seconds to fetch data from data provider due to rate limit.
#  Confidence         uint8  `json:"confidence" yaml:"confidence"` // The confidence of the data that are going to be sourced from the provider's service. Valid range is [0, 100].
#  // Below configurations are reserved only for on-chain AMM marketplaces.
#  NTNTokenAddress  string `json:"ntnTokenAddress" yaml:"ntnTokenAddress"`   // The NTN erc20 token address on the target blockchain.
#  ATNTokenAddress  string `json:"atnTokenAddress" yaml:"atnTokenAddress"`   // The Wrapped ATN erc20 token address on the target blockchain.
#  USDCTokenAddress string `json:"usdcTokenAddress" yaml:"usdcTokenAddress"` // The USDC erc20 token address on the target blockchain.
#  SwapAddress      string `json:"swapAddress" yaml:"swapAddress"`           // The UniSwap factory contract address or AirSwap SwapERC20 contract address on the target blockchain.
}

# Un-comment below lines to enable your forex data plugin's configuration on demand. Your production configurations start from below:
#pluginConfigs:
#  - name: forex_currencyfreaks              # required, it is the plugin file name in the plugin directory.
#    key: 175aab9e47e54790bf6d502c48407c10   # required, visit https://currencyfreaks.com to get your key, and replace it.
#    confidence: 60                          # optional, the user can decide the data confidence base on the data quality of the data service. Valid range is [0, 100], the higher value the better data quality is.
#    refresh: 3600                           # optional, buffered data within 3600s, recommended for API rate limited data source.

#  - name: forex_openexchange                # required, it is the plugin file name in the plugin directory.
#    key: 1be02ca33c4843ee968c4cedd2686f01   # required, visit https://openexchangerates.org to get your key, and replace it.
#    confidence: 60                          # optional, the user can decide the data confidence base on the data quality of the data service. Valid range is [0, 100], the higher value the better data quality is.
#    refresh: 3600                           # optional, buffered data within 3600s, recommended for API rate limited data source.

#  - name: forex_currencylayer               # required, it is the plugin file name in the plugin directory.
#    key: 105af082ac7f7d150c87303d4e2f049e   # required, visit https://currencylayer.com  to get your key, and replace it.
#    confidence: 60                          # optional, the user can decide the data confidence base on the data quality of the data service. Valid range is [0, 100], the higher value the better data quality is.
#    refresh: 3600                           # optional, buffered data within 3600s, recommended for API rate limited data source.

#  - name: forex_exchangerate                # required, it is the plugin file name in the plugin directory.
#    key: 111f04e4775bb86c20296530           # required, visit https://www.exchangerate-api.com to get your key, and replace it.
#    confidence: 60                          # optional, the user can decide the data confidence base on the data quality of the data service. Valid range is [0, 100], the higher value the better data quality is.
#    refresh: 3600                           # optional, buffered data within 3600s, recommended for API rate limited data source.

#  - name: forex_wise                        # required, it is the plugin file name in the plugin directory.
#    key: 1234                               # required, visit https://www.wise.com to get your key, and replace it.
#    confidence: 60                          # optional, the user can decide the data confidence base on the data quality of the data service. Valid range is [0, 100], the higher value the better data quality is.
#    refresh: 30                             # optional, buffered data within 30s, recommended for API rate limited data source.
# Un-comment below lines to config the RPC endpoint of a Piccadilly Network Validator Node for your AMM plugin which sources ATN & NTN market data from an on-chain AMM.
#  - name: crypto_uniswap
#    scheme: "wss"                           # Only websocket please, available values are: "ws" or "wss", default value is "wss" for uniswap plugins.
#    confidence: 60                          # optional, the user can decide the data confidence base on the data quality of the data service. Valid range is [0, 100], the higher value the better data quality is.
#    endpoint: "rpc-internal-1.piccadilly.autonity.org/ws"  # The default URL might not be stable for public usage, we recommend you to change it with your validator node's RPC endpoint.

#Enable the metric collection for oracle server, supported TS-DB engines are influxDB v1 and v2.
#metricConfigs:
#  influxDBEndpoint: "http://localhost:8086"
#  influxDBTags: "host=localhost"
#  enableInfluxDB: false
#  influxDBDatabase: "autonity"
#  influxDBUsername: "test"
#  influxDBPassword: "test"
#  enableInfluxDBV2: false
#  influxDBToken: "test"
#  influxDBBucket: "autonity"
#  influxDBOrganization: "autonity"
