# A list of plugins with each one's executable binary name and its corresponding API key granted by the data provider.
# For forex data providers which provide the realtime exchange rate of EUR/USD, JPY/USD, GBP/USD, AUD/USD, CAD/USD and
# SEK/USD, there are 5 official plugins listed below, end user can select one or more of them on-demand for the forex
# data sourcing. Remember to config the API key in below once you subscribe the service plan from your data vendors.

# Un-comment below lines to enable your configuration on demand.
#  - name: forex_currencyfreaks              # visit https://currencyfreaks.com to apply for your key
#    key: 575aab9e47e54790bf6d502c48407c10   # replace it with your own key

#  - name: forex_openexchangerate            # visit https://openexchangerates.org to apply for your key
#    key: 0be02ca33c4843ee968c4cedd2686f01   # replace it with your own key

#  - name: forex_currencylayer               # visit https://currencylayer.com to apply for your key
#    key: 705af082ac7f7d150c87303d4e2f049e   # replace it with your own key

#  - name: forex_exchangerate                # vist https://www.exchangerate-api.com to apply for your key
#    key: 411f04e4775bb86c20296530           # replace it with your own key
